{
 "title": "Stock share monitoring",
 "description": "Watch the price of the stock shares you own. For more detail : https://github.com/pbrissaud/suivi-bourse-app",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "bucket", "label": "Bucket", "query": "buckets()" },
   {
    "name": "share",
    "label": "Share",
    "query": "import \"influxdata/influxdb/v1\"\n\nv1.measurementTagValues(bucket: \"${bucket}\", measurement: \"estate\", tag: \"name\")"
   }
  ]
 },
 "panels": [
  { "title": "$share", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "share" },
  {
   "title": "Share price evolution",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "alias": "Share mean price on 5min",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "price",
     "query": "FinalOutput = [\"_field\", \"_time\", \"_value\"]\n\nRawSeries = from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"price\")\n  |> filter(fn: (r) => r[\"_field\"] == \"amount\")\n  |> filter(fn: (r) => r[\"name\"] == \"${share}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n\nNamedSeries = RawSeries\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"Share mean price on 5min\"}))\n  |> keep(columns:FinalOutput)\n\nNamedSeries |> yield()",
     "select": [
      [
       { "params": [ "amount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$share$/" }
     ]
    }
   ]
  },
  {
   "title": "Purchased quantity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "purchase",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"purchase\")\n  |> filter(fn: (r) => r[\"_field\"] == \"quantity\")\n  |> filter(fn: (r) => r[\"name\"] == \"${share}\" )\n  |> last()",
     "select": [
      [
       { "params": [ "quantity" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$share$/" }
     ]
    }
   ]
  },
  {
   "title": "Cost price",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "purchase",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"purchase\")\n  |> filter(fn: (r) => r[\"_field\"] == \"cost_price\")\n  |> filter(fn: (r) => r[\"name\"] == \"${share}\" )\n  |> last()",
     "select": [
      [
       { "params": [ "cost_price" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$share$/" }
     ]
    }
   ]
  },
  {
   "title": "Fees",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "purchase",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"purchase\")\n  |> filter(fn: (r) => r[\"_field\"] == \"fee\")\n  |> filter(fn: (r) => r[\"name\"] == \"${share}\" )\n  |> last()",
     "select": [
      [
       { "params": [ "fee" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$share$/" }
     ]
    }
   ]
  },
  {
   "title": "Actual price",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "price",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"price\")\n  |> filter(fn: (r) => r[\"_field\"] == \"amount\")\n  |> filter(fn: (r) => r[\"name\"] == \"${share}\")\n  |> last()\n",
     "select": [
      [
       { "params": [ "amount" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$share$/" }
     ]
    }
   ]
  },
  {
   "title": "Unitary Gain / Loss ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "actual",
     "measurement": "price",
     "query": "actual = from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"price\")\n  |> filter(fn: (r) => r[\"_field\"] == \"amount\")\n  |> filter(fn: (r) => r[\"name\"] == \"${share}\")\n  |> last()\n\ncost = from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"purchase\")\n  |> filter(fn: (r) => r[\"_field\"] == \"cost_price\")\n  |> filter(fn: (r) => r[\"name\"] == \"${share}\" )\n  |> last()\n\njoin(tables: {cost:cost, actual:actual}, on: [\"_time\", \"_stop\",\"_start\"])\n|> map(fn: (r) => ({\n    _time: r._time,\n    _value: (r._value_actual - r._value_cost)\n}))",
     "select": [
      [
       { "params": [ "amount" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$share$/" }
     ]
    }
   ]
  },
  {
   "title": "Owned quantity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "estate",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"estate\")\n  |> filter(fn: (r) => r[\"_field\"] == \"quantity\")\n  |> filter(fn: (r) => r[\"name\"] == \"${share}\" )\n  |> last()",
     "select": [
      [
       { "params": [ "quantity" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$share$/" }
     ]
    }
   ]
  },
  {
   "title": "Received dividend",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "estate",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"estate\")\n  |> filter(fn: (r) => r[\"_field\"] == \"received_dividend\")\n  |> filter(fn: (r) => r[\"name\"] == \"${share}\" )\n  |> last()",
     "select": [
      [
       { "params": [ "received_dividend" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$share$/" }
     ]
    }
   ]
  },
  {
   "title": "Total gain / loss",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "actual_price",
     "measurement": "price",
     "query": "cost_price = from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"purchase\")\n  |> filter(fn: (r) => r[\"_field\"] == \"cost_price\")\n  |> filter(fn: (r) => r[\"name\"] == \"${share}\" )\n  |> last()\n\npurchase_quantity = from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"purchase\")\n  |> filter(fn: (r) => r[\"_field\"] == \"quantity\")\n  |> filter(fn: (r) => r[\"name\"] == \"${share}\" )\n  |> last()\n\npurchase_value = join(tables: {cost_price:cost_price, purchase_quantity:purchase_quantity}, on: [\"_time\", \"_stop\",\"_start\"])\n|> map(fn: (r) => ({\n    _time: r._time,\n    _value: (r._value_purchase_quantity * r._value_cost_price)\n}))\n\nprice = from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"price\")\n  |> filter(fn: (r) => r[\"_field\"] == \"amount\")\n  |> filter(fn: (r) => r[\"name\"] == \"${share}\")\n  |> last()\n\nactual_quantity = from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"estate\")\n  |> filter(fn: (r) => r[\"_field\"] == \"quantity\")\n  |> filter(fn: (r) => r[\"name\"] == \"${share}\" )\n  |> last()\n\nactual_value = join(tables: {price:price, actual_quantity:actual_quantity}, on: [\"_time\", \"_stop\",\"_start\"])\n|> map(fn: (r) => ({\n    _time: r._time,\n    _value: (r._value_actual_quantity * r._value_price)\n}))\n\ndelta = join(tables: {actual_value:actual_value, purchase_value:purchase_value}, on: [\"_time\"])\n  |> map(fn: (r) => ({\n    _time: r._time,\n    _value: (r._value_actual_value - r._value_purchase_value)\n}))\n\nfees = from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"purchase\")\n  |> filter(fn: (r) => r[\"_field\"] == \"fee\")\n  |> filter(fn: (r) => r[\"name\"] == \"${share}\" )\n  |> last()\n\ndelta_fees = join(tables: {delta:delta, fees:fees}, on: [\"_time\"])\n  |> map(fn: (r) => ({\n    _time: r._time,\n    _value: (r._value_delta - r._value_fees)\n}))\n\ndividend = from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"estate\")\n  |> filter(fn: (r) => r[\"_field\"] == \"received_dividend\")\n  |> filter(fn: (r) => r[\"name\"] == \"${share}\" )\n  |> last()\n\njoin(tables: {delta_fees:delta_fees, dividend:dividend}, on: [\"_time\"])\n  |> map(fn: (r) => ({\n    _time: r._time,\n    _value: (r._value_delta_fees + r._value_dividend)\n}))",
     "select": [
      [
       { "params": [ "amount" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$share$/" }
     ]
    }
   ]
  }
 ]
}