apiVersion: 1
datasources:
  - name: InfluxDB
    type: influxdb
    url: http://influxdb:8181
    access: proxy
    editable: false
    jsonData:
      version: SQL
      httpMode: POST
      dbName: suivi_bourse
      insecureGrpc: true
      tlsSkipVerify: true
    secureJsonData:
      token: apiv3_suivi-bourse-admin-token-for-local-development
