/**
 * **A grid states its column at every width it is drawn at** (#787), held on the
 * source because nothing makes it true by construction and no rendering test
 * could see it.
 *
 * The defect it closes was on every page at once and looked like a mystery: at
 * 390 px the cards ran off the right edge of the screen, and nothing inside them
 * was too wide — every long name carried a `truncate`, every table its own
 * scroller. The cause is a CSS rule with no visible symptom until it bites.
 *
 * `<div class="grid gap-6 lg:grid-cols-2">` declares **no** column template
 * below `lg`. The implicit track is then `auto`, which is
 * `minmax(min-content, max-content)` — so the column grows to whatever the
 * widest unbreakable thing inside it needs, *past its own container*, and every
 * `w-full` under it inherits the new width. On the accounts page one event
 * label — `Interest payment for payout collection 019fbad1-…` — took a 375 px
 * column to 616. The `truncate` never fired: there was nothing left to truncate
 * against, the box having grown to fit.
 *
 * `grid-cols-1` is `repeat(1, minmax(0, 1fr))`, and the `0` is the whole of it:
 * a floor of zero lets the track be as narrow as its container, which is what
 * puts the truncations back in charge.
 *
 * So the rule: **a `grid` that names a column at a breakpoint names one without
 * a breakpoint too.** A grid with no column template anywhere is untouched — one
 * `auto` column is the correct answer when nothing has asked for more.
 */
import fs from 'node:fs'
import path from 'node:path'
import { describe, expect, it } from 'vitest'

const ROOT = path.resolve(import.meta.dirname, '..')
const SOURCE = path.join(ROOT, 'src')

function sources(directory: string): string[] {
  return fs.readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const full = path.join(directory, entry.name)
    if (entry.isDirectory()) return sources(full)
    // The suite is not judged, and neither is the component library: `ui/` is
    // generated by shadcn and regenerated from the registry (ADR-0023), so a
    // rule enforced there would be undone by the next `add`.
    if (!/\.tsx$/.test(entry.name) || /\.test\.tsx$/.test(entry.name)) return []
    if (full.includes(`${path.sep}ui${path.sep}`)) return []
    return [full]
  })
}

/** Every `class`-ish string literal the file holds, however it is spelled. */
function classLists(source: string): string[] {
  return [...source.matchAll(/'([^'\n]*\bgrid\b[^'\n]*)'|"([^"\n]*\bgrid\b[^"\n]*)"/g)].map(
    (match) => match[1] ?? match[2],
  )
}

const BREAKPOINT_COLUMNS = /\b(?:sm|md|lg|xl|2xl):grid-cols-/
const BASE_COLUMNS = /(?:^|\s)grid-cols-/

describe('a grid states its column at every width it is drawn at', () => {
  const offenders: string[] = []

  for (const file of sources(SOURCE)) {
    const relative = path.relative(ROOT, file)
    for (const list of classLists(fs.readFileSync(file, 'utf8'))) {
      if (!/(?:^|\s)grid(?:\s|$)/.test(list)) continue
      if (!BREAKPOINT_COLUMNS.test(list)) continue
      if (BASE_COLUMNS.test(list)) continue
      offenders.push(`${relative} — "${list}"`)
    }
  }

  it('names a base template wherever it names one at a breakpoint', () => {
    expect(offenders).toEqual([])
  })

  it('reads the class lists it is supposed to be reading', () => {
    // The coverage half, and it is not decoration: a regex that stopped matching
    // would make the assertion above pass on a front that had lost the rule
    // entirely — the failure `readsInFlight.test.tsx` and `inFlightShape.test.ts`
    // each owe the same half to.
    const seen = sources(SOURCE).flatMap((file) =>
      classLists(fs.readFileSync(file, 'utf8')).filter((list) => BREAKPOINT_COLUMNS.test(list)),
    )
    expect(seen.length).toBeGreaterThan(5)
  })
})
