/**
 * **There is no spinner, and no skeleton, anywhere in the front** (#795,
 * ADR-0026, ADR-0031), held on the source because no rendering test can see it.
 *
 * The rule is old — a block waiting on a needed read renders *nothing at all*,
 * and a frame with an empty body **is** a hand-written skeleton — and
 * `readsInFlight.test.tsx` holds the half that is observable: what a surface
 * *says* while a read hangs. What it cannot see is a shape that says nothing: a
 * turning circle carries no word, an `animate-pulse` grey block carries no word,
 * and the net that reads every rendered phrase walks straight past both.
 *
 * ADR-0031 is what makes the gap worth a file of its own. It puts a control
 * under a paginated table and then writes down, in as many words, that the
 * absence of a spinner there is *"the kind of rule that breaks in silence when
 * the next contributor adds a spinner back"* — because a *load more* button is
 * exactly the place a reader of the code expects one, and here there is not even
 * a wait to dress: the next forty rows are already in memory.
 *
 * So the vocabulary is refused at the source. `_Avoid_: loading, pending,
 * spinner, skeleton` is a rule about what the product renders, and this is the
 * one place it can be asserted.
 *
 * **`ui/` is exempt, and the exemption has a floor.** That directory is
 * generated by shadcn and regenerated from the registry (ADR-0023), so a rule
 * enforced inside it would be undone by the next `add` — `ui/skeleton.tsx` and
 * `SidebarMenuSkeleton` are both the registry's, and both are dead code here.
 * What is asserted instead is that **nothing outside `ui/` reaches for them**,
 * which is the fact that actually matters: a generated component nobody imports
 * renders on no page.
 */
import fs from 'node:fs'
import path from 'node:path'
import { describe, expect, it } from 'vitest'

const ROOT = path.resolve(import.meta.dirname, '..')
const SOURCE = path.join(ROOT, 'src')

/** Every source of the app itself — not the suite, and not the registry's. */
function sources(directory: string): string[] {
  return fs.readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const full = path.join(directory, entry.name)
    if (entry.isDirectory()) return sources(full)
    if (!/\.tsx?$/.test(entry.name) || /\.test\.tsx?$/.test(entry.name)) return []
    if (full.includes(`${path.sep}ui${path.sep}`)) return []
    if (full.includes(`${path.sep}test${path.sep}`)) return []
    return [full]
  })
}

/**
 * The forms a wait is dressed in, and each is **code** rather than prose: this
 * file is surrounded by comments explaining why a skeleton is refused, and a
 * pattern matching the word would fail on the explanation of the rule it holds.
 */
const DRESSED: readonly (readonly [string, RegExp])[] = [
  ['a turning circle', /\banimate-spin\b/],
  ['a pulsing block', /\banimate-pulse\b/],
  ['the registry’s skeleton', /<Skeleton\b|\bfrom ['"][^'"]*\/skeleton['"]/],
  ['a progress bar', /role=["']progressbar["']/],
  ['a busy region', /\baria-busy\b/],
]

describe('a wait is never dressed, because there is never a wait to dress', () => {
  const offenders: string[] = []
  const files = sources(SOURCE)

  for (const file of files) {
    const source = fs.readFileSync(file, 'utf8')
    for (const [what, pattern] of DRESSED) {
      if (pattern.test(source)) offenders.push(`${path.relative(ROOT, file)} — ${what}`)
    }
  }

  it('renders no spinner, no skeleton and no progress bar on any surface', () => {
    expect(offenders).toEqual([])
  })

  it('reads the sources it is supposed to be reading', () => {
    // The coverage half, in the taste of `gridColumns.test.ts`: a walk that
    // stopped finding files would make the assertion above pass on a front that
    // had lost the rule entirely.
    expect(files.length).toBeGreaterThan(30)
    expect(files.some((file) => file.endsWith(`data${path.sep}Ledger.tsx`))).toBe(true)
    // And the patterns themselves catch what they are written to catch, on a
    // string this file owns rather than on the front's own text.
    const planted =
      '<div className="animate-spin animate-pulse" aria-busy role="progressbar"><Skeleton /></div>'
    expect(DRESSED.filter(([, pattern]) => !pattern.test(planted)).map(([what]) => what)).toEqual([])
  })
})
