/**
 * **One component draws a share** (#800), held on the source because nothing
 * makes it true by construction and no rendering test can see it.
 *
 * The rule is the ticket's central criterion and its reason is the product's
 * own history: `Stat`, `EmptyState`, `Refusal` and `EntryPair` all exist because
 * the prototype held four copies of one thing, and a share bar written three
 * times diverges three times. It had already started — the allocation's legend
 * wrote none, the rail wrote one, and the account's composition wrote a second
 * with its own height, its own clamp and its own answer to a missing whole.
 *
 * A rendering test cannot hold it. A bar is `aria-hidden` and carries no word,
 * so `readsInFlight.test.tsx`, which reads every rendered phrase, walks past it
 * exactly as it walks past a spinner — which is the gap `noSpinner.test.ts` was
 * written for, one file over. What is left to assert is the shape of the
 * *source*: a percentage width, computed and written into a `style`, is what a
 * hand-written share bar is made of, and there is one place it belongs.
 *
 * **The stacked bar is the one exemption, and it has a floor.** The rail draws
 * the accounts as adjacent segments closing a whole, which is a claim about the
 * total that no per-line bar makes (`AccountsRail.tsx` carries the argument for
 * keeping both). Its segments are therefore not `ShareBar`s and cannot be. So
 * the exemption is not *this file may do as it likes*: the offenders are
 * asserted to be **exactly** that one bar, by file, which is what makes a second
 * hand-written bar in the same file fail like a hand-written bar anywhere else.
 */
import fs from 'node:fs'
import path from 'node:path'
import { describe, expect, it } from 'vitest'

const ROOT = path.resolve(import.meta.dirname, '..')
const SOURCE = path.join(ROOT, 'src')

/** The primitive itself, which is the one place a share may be drawn. */
const PRIMITIVE = path.join(SOURCE, 'components', 'ShareBar.tsx')

/**
 * The stacked bar of the accounts rail — kept, argued for on the file, and
 * spelled here so that it is an exemption of one drawing rather than of a file.
 */
const STACKED_BAR = 'src/components/accounts/AccountsRail.tsx'

/**
 * The surfaces that draw a share, spelled out — the other half of the rule.
 *
 * Refusing hand-written bars everywhere says nothing about there being a bar at
 * all: delete `<ShareBar />` from the allocation's legend and every other test
 * still passes, the drawing carrying no word for a rendering test to miss. The
 * rail's own bar is read in the DOM by `accounts.test.tsx`, which is the
 * stronger assertion of the two and is why this list is a *floor* rather than a
 * replacement for it. The shares table's `Poids` column joined the list at #791,
 * left again when the column did, and is back with it (#832) — the drawing being
 * the whole reason the column came back: `ShareBar` is the primitive this file
 * was written ahead of, and the shares table is the surface it was written for.
 */
const MOUNTS = [
  'src/components/dashboard/Allocation.tsx',
  'src/components/accounts/AccountsRail.tsx',
  'src/components/accounts/AccountDetail.tsx',
  'src/components/shares/SharesTable.tsx',
]

function sources(directory: string): string[] {
  return fs.readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const full = path.join(directory, entry.name)
    if (entry.isDirectory()) return sources(full)
    // The suite is not judged, and neither is the component library: `ui/` is
    // generated by shadcn and regenerated from the registry (ADR-0023), so a
    // rule enforced there would be undone by the next `add`.
    if (!/\.tsx?$/.test(entry.name) || /\.test\.tsx?$/.test(entry.name)) return []
    if (full.includes(`${path.sep}ui${path.sep}`)) return []
    if (full.includes(`${path.sep}test${path.sep}`)) return []
    return [full]
  })
}

/**
 * A width in per cent, written into a `style` from a value the file computed.
 *
 * It matches the drawing and not the arithmetic: `share * 100` on its own is a
 * percentage a surface is about to *write out*, which is what `f.percentPoints`
 * is for and is no business of this net's. What is refused is that number
 * reaching a `width`.
 */
const DRAWN_WIDTH = /\bwidth:\s*[`'"]\s*\$\{[^`'"]*\}\s*%/

describe('one component draws a share', () => {
  const offenders: string[] = []

  for (const file of sources(SOURCE)) {
    if (file === PRIMITIVE) continue
    if (DRAWN_WIDTH.test(fs.readFileSync(file, 'utf8'))) offenders.push(path.relative(ROOT, file))
  }

  it('leaves every share bar to the primitive, the stacked bar apart', () => {
    // Exactly the stacked bar, and nothing beside it: the `Poids` column of the
    // shares table (#832) mounts `ShareBar`, which is why it is not here.
    expect(offenders).toEqual([STACKED_BAR])
  })

  it.each(MOUNTS)('is mounted by %s, which draws a share', (file) => {
    expect(fs.readFileSync(path.join(ROOT, file), 'utf8')).toContain('<ShareBar')
  })

  it('reads the widths it is supposed to be reading', () => {
    // The coverage half, in the taste of `gridColumns.test.ts` and
    // `noSpinner.test.ts`: a pattern that stopped matching would make the
    // assertion above pass on a front that had lost the rule entirely — and it
    // would pass *loudly*, the stacked bar's own line being the first thing it
    // stopped seeing.
    expect(DRAWN_WIDTH.test(fs.readFileSync(PRIMITIVE, 'utf8'))).toBe(true)
    expect(sources(SOURCE).length).toBeGreaterThan(20)
  })
})
