// @ts-check

/**
 * The v5 corpus is a flat thread and carries no category: the head is the
 * trajectory of someone arriving, the tail explains the machine to someone
 * already running it.
 *
 * The order **is** the taxonomy, so it is written here as an explicit list and
 * read from one place — not spread over a dozen `sidebar_position` headers, and
 * not `autogenerated`, which would hand the order back to the filesystem and
 * re-create categories out of directories.
 *
 * It lost `headless-gauges` when the gauges went with `/metrics`: there is one
 * interface now, so there is no second usage to give a page to. It regained an
 * entry with the agent's interface, and the difference is the reason the first
 * one left — `/metrics` was a second usage of the product; the agent's
 * interface is the *same* usage reached by something other than a browser.
 *
 * `your-taxation-model` sits after `read-your-figures` (#954) for the same
 * reason: it is not a twelfth subject, it is where the projected-tax rule sends
 * a reader who has just met the figure and wants to know where the rate it
 * names is recorded.
 */

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'home',
    'get-started',
    'import-your-events',
    'read-your-figures',
    'your-taxation-model',
    'settings',
    'install-without-docker',
    'rebuild-and-resolution',
    'how-prices-are-collected',
    'connect-your-own-agent',
    'coming-from-v4',
    'release-notes',
  ],
};

module.exports = sidebars;
