// @ts-check

/**
 * The v5 corpus is a flat thread of eleven entries and carries no category
 * (ADR-0025): the head is the trajectory of someone arriving, the tail explains
 * the machine to someone already running it.
 *
 * The order **is** the taxonomy, so it is written here as an explicit list and
 * read from one place — not spread over eleven `sidebar_position` headers, and
 * not `autogenerated`, which would hand the order back to the filesystem and
 * re-create categories out of directories.
 *
 * A page whose *usage* is headless (`headless-gauges`) is an entry of this same
 * thread: giving it a branch would make it optional again, which is the split
 * ADR-0014 and ADR-0015 removed from the product.
 */

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'home',
    'get-started',
    'import-your-events',
    'read-your-figures',
    'settings',
    'install-without-docker',
    'rebuild-and-resolution',
    'how-prices-are-collected',
    'headless-gauges',
    'coming-from-v4',
    'release-notes',
  ],
};

module.exports = sidebars;
