// @ts-check

/**
 * The v5 corpus is a flat thread of ten entries and carries no category
 * (ADR-0025): the head is the trajectory of someone arriving, the tail explains
 * the machine to someone already running it.
 *
 * The order **is** the taxonomy, so it is written here as an explicit list and
 * read from one place — not spread over ten `sidebar_position` headers, and
 * not `autogenerated`, which would hand the order back to the filesystem and
 * re-create categories out of directories.
 *
 * It was eleven until `headless-gauges` went with `/metrics` (ADR-0033). The
 * thread lost an entry rather than gaining a rewritten one: there is one
 * interface now, so there is no second usage to give a page to.
 */

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'home',
    'get-started',
    'import-your-events',
    'read-your-figures',
    'settings',
    'install-without-docker',
    'rebuild-and-resolution',
    'how-prices-are-collected',
    'coming-from-v4',
    'release-notes',
  ],
};

module.exports = sidebars;
