name: "Pull request checks"
on:
  pull_request:
    branches: [master]

jobs:
  python-linter:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: ricardochaves/python-lint@v1.4.0
        with:
          python-root-list: "app/src/"
          use-pycodestyle: false
          use-pylint: false
          use-black: false
          use-mypy: false
          use-isort: false
          extra-flake8-options: "--ignore=E501"

  unit-test:
    name: "Unit Test"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: astral-sh/setup-uv@v8.2.0
        with:
          enable-cache: true

      - run: cd app && uv run pytest tests/

  build-docs:
    name: "Building doc"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Get changed files in the docs folder
        id: changed-files-specific
        uses: tj-actions/changed-files@v47
        with:
          files: |
            website/**
      - name: Build docs if folder changed
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        working-directory: website
        run: |
          yarn install
          yarn build
