name: "Pull request compliance"
on:
  pull_request:
    types: [ opened, synchronize, reopened, edited ]
    branches:
      - master

permissions:
  pull-requests: write

jobs:
  dco-check:
    name: DCO Check
    runs-on: ubuntu-latest
    steps:
      - uses: tisonkun/actions-dco@v1.1

  validate-pr-title:
    name: PR Title Validation
    runs-on: ubuntu-latest
    steps:
      - name: PR Conventional Commit Validation
        uses: ytanikin/PRConventionalCommits@1.3.0
        with:
          task_types: '["feat","fix", "feat!", "fix!", "refactor!", "deps", "chore", "docs"]'